{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Executor.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyMzJilITPIwDmH7a446yPs9"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","metadata":{"id":"oL2sNFPYlpKV"},"source":["## Drive Mount + Git Pull Push"]},{"cell_type":"code","metadata":{"id":"TMTZS92Mi5xG","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1618792478670,"user_tz":240,"elapsed":368,"user":{"displayName":"Wyler Zahm","photoUrl":"","userId":"14161046984783343247"}},"outputId":"70aa6465-4efe-4ba2-c869-0b63a92d6e03"},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","%cd drive/Shareddrives/EECS\\ 442\\ -\\ Project/eecs442-proj\n","!pip install -r requirements.txt"],"execution_count":2,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"UpcVLjTojBzk"},"source":["#!git config --global user.email \"wzahm@umich.edu\"\n","#!git config --global user.name \"Wyler Zahm\"\n","#!git pull\n","!git add *\n","!git commit -m \"COLAB COMMIT\"\n","!git push\n","!git status\n","#!git pull\n","#!git add Executor.ipynb metrics.ipynb\n","#!git commit -m \"Adding executor noteboook.\"\n","\n","#!git push\n","#!git push"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"PPhDJM3rllza"},"source":["## Data Downloading"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":566},"id":"KRMTv9S_jVmB","executionInfo":{"status":"ok","timestamp":1618794357242,"user_tz":240,"elapsed":10151,"user":{"displayName":"Wyler Zahm","photoUrl":"","userId":"14161046984783343247"}},"outputId":"d54a5540-d071-4186-9045-3c387fe24b91"},"source":["#!pip install -r requirements.txt\n","#%cd diode\n","#!wget http://diode-dataset.s3.amazonaws.com/val.tar.gz\n","#!tar -zxvf val.tar.gz\n","#%cd ..\n","\n","#!wget https://download.pytorch.org/models/densenet169-b2777c0a.pth\n","\n","!pip uninstall matplotlib\n","!pip install matplotlib"],"execution_count":29,"outputs":[{"output_type":"stream","text":["Uninstalling matplotlib-3.1.3:\n","  Would remove:\n","    /usr/local/lib/python3.7/dist-packages/matplotlib-3.1.3-py3.7-nspkg.pth\n","    /usr/local/lib/python3.7/dist-packages/matplotlib-3.1.3.dist-info/*\n","    /usr/local/lib/python3.7/dist-packages/matplotlib/*\n","    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axes_grid/*\n","    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axes_grid1/*\n","    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axisartist/*\n","    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/mplot3d/*\n","    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/tests/*\n","    /usr/local/lib/python3.7/dist-packages/pylab.py\n","Proceed (y/n)? y\n","  Successfully uninstalled matplotlib-3.1.3\n","Collecting matplotlib\n","  Using cached https://files.pythonhosted.org/packages/ce/63/74c0b6184b6b169b121bb72458818ee60a7d7c436d7b1907bd5874188c55/matplotlib-3.4.1-cp37-cp37m-manylinux1_x86_64.whl\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (0.10.0)\n","Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.20.2)\n","Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (2.4.7)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.3.1)\n","Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (2.8.1)\n","Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (8.2.0)\n","Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from cycler>=0.10->matplotlib) (1.15.0)\n","\u001b[31mERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.\u001b[0m\n","Installing collected packages: matplotlib\n","Successfully installed matplotlib-3.4.1\n"],"name":"stdout"},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["matplotlib","mpl_toolkits"]}}},"metadata":{"tags":[]}}]},{"cell_type":"markdown","metadata":{"id":"IThgclscltOx"},"source":["## Model Exection"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"tvVqnP9Klj_1","executionInfo":{"status":"error","timestamp":1618794364748,"user_tz":240,"elapsed":2197,"user":{"displayName":"Wyler Zahm","photoUrl":"","userId":"14161046984783343247"}},"outputId":"94b58c5d-e8a6-47c0-de52-614b0cf7782e"},"source":["%load_ext autoreload\n","%autoreload 2\n","from model_pipeline import main as exec_model\n","\n","exec_model()"],"execution_count":30,"outputs":[{"output_type":"stream","text":["[autoreload of matplotlib failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","AttributeError: module 'matplotlib.rcsetup' has no attribute '_validators'\n","]\n","[autoreload of matplotlib.cbook failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: connect() requires a code object with 0 free vars, not 4\n","]\n","/usr/lib/python3.7/importlib/__init__.py:169: MatplotlibDeprecationWarning: The module matplotlib.cbook.deprecation is considered internal and it will be made private in the future.\n","  _bootstrap._exec(spec, module)\n","[autoreload of matplotlib.rcsetup failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: validate_anylist() requires a code object with 2 free vars, not 3\n","]\n","[autoreload of matplotlib.colors failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.docstring failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: from_params() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.pyplot failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'Axes_kwdoc'\n","]\n","[autoreload of matplotlib.colorbar failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 3\n","]\n","[autoreload of matplotlib.artist failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: set_contains() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.path failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: cleaned() requires a code object with 0 free vars, not 9\n","]\n","[autoreload of matplotlib.transforms failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __copy__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.collections failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'CapStyle'\n","]\n","[autoreload of matplotlib.cm failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: add_checker() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.lines failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'JoinStyle'\n","]\n","[autoreload of matplotlib.markers failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: set_fillstyle() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.contour failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: get_rotation() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.ticker failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.text failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.patches failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'CapStyle'\n","]\n","[autoreload of matplotlib.bezier failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: find_bezier_t_intersecting_with_closedpath() requires a code object with 4 free vars, not 0\n","]\n","[autoreload of matplotlib.textpath failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: get_text_path() requires a code object with 3 free vars, not 0\n","]\n","[autoreload of matplotlib.dviread failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","RecursionError: maximum recursion depth exceeded while calling a Python object\n","]\n","[autoreload of matplotlib.mathtext failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.texmanager failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: make_tex_preview() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.blocking_input failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.gridspec failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.image failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: set_interpolation() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.backend_bases failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'CapStyle'\n","]\n","[autoreload of matplotlib.backend_tools failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.widgets failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","Bad val 'round' on line #19\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn-white.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #19\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn-whitegrid.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'butt' on line #26\n","\t\"lines.solid_capstyle: butt\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/Solarize_Light2.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'butt' on line #5\n","\t\"lines.solid_capstyle: butt\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/fivethirtyeight.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'path' on line #21\n","\t\"svg.fonttype: path\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/fivethirtyeight.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #19\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn-darkgrid.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #19\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn-ticks.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #15\n","\t\"lines.dash_joinstyle : round        # miter|round|bevel\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'butt' on line #16\n","\t\"lines.dash_capstyle : butt          # butt|round|projecting\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #17\n","\t\"lines.solid_joinstyle : round       # miter|round|bevel\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'projecting' on line #18\n","\t\"lines.solid_capstyle : projecting   # butt|round|projecting\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'full' on line #26\n","\t\"markers.fillstyle: full\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'cm' on line #158\n","\t\"mathtext.fontset : cm # Should be 'cm' (Computer Modern), 'stix',\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","\n","Bad key \"mathtext.fallback\" on line 160 in\n","/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle.\n","You probably need to get an updated matplotlibrc file from\n","https://github.com/matplotlib/matplotlib/blob/v3.2.2/matplotlibrc.template\n","or from the matplotlib source distribution\n","Bad val 'major' on line #178\n","\t\"axes.grid.which     : major\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'both' on line #179\n","\t\"axes.grid.axis      : both\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","\n","Bad key \"axes.titley\" on line 181 in\n","/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle.\n","You probably need to get an updated matplotlibrc file from\n","https://github.com/matplotlib/matplotlib/blob/v3.2.2/matplotlibrc.template\n","or from the matplotlib source distribution\n","Bad val 'round_numbers' on line #218\n","\t\"axes.autolimit_mode : round_numbers\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","\n","Bad key \"date.converter\" on line 235 in\n","/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle.\n","You probably need to get an updated matplotlibrc file from\n","https://github.com/matplotlib/matplotlib/blob/v3.2.2/matplotlibrc.template\n","or from the matplotlib source distribution\n","Bad val 'center' on line #256\n","\t\"xtick.alignment : center\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'center' on line #274\n","\t\"ytick.alignment      : center\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'upper right' on line #285\n","\t\"legend.loc           : upper right\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'upper' on line #334\n","\t\"image.origin : upper             # lower | upper\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'portrait' on line #429\n","\t\"savefig.orientation : portrait\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'letter' on line #432\n","\t\"ps.papersize      : letter   # auto, letter, legal, ledger, A0-A10, B0-B10\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'xelatex' on line #449\n","\t\"pgf.texsystem       : xelatex\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'path' on line #455\n","\t\"svg.fonttype : path            # How to handle SVG fonts:\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'ffmpeg' on line #476\n","\t\"animation.writer : ffmpeg         # MovieWriter 'backend' to use\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'png' on line #480\n","\t\"animation.frame_format: png       # Controls frame format used by temp files\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'none' on line #488\n","\t\"animation.html: none\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","In /usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: \n","The validate_nseq_float function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.\n","In /usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: \n","The _make_nseq_validator function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.\n","Bad val 'round' on line #19\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn-dark.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'round' on line #34\n","\t\"lines.solid_capstyle: round\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/seaborn.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'center_baseline' on line #6\n","\t\"ytick.alignment: center_baseline\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","Bad val 'cm' on line #13\n","\t\"mathtext.fontset : cm\n","\"\n","\tin file \"/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/bmh.mplstyle\"\n","\t'ValidateInStrings' object has no attribute '_deprecated_since'\n","[autoreload of matplotlib.figure failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'Axes_kwdoc'\n","]\n","[autoreload of matplotlib.axes._subplots failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'Axes'\n","]\n","[autoreload of matplotlib.axes._axes failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ImportError: cannot import name '_TransformedBoundsLocator' from 'matplotlib.axes._base' (/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_base.py)\n","]\n","[autoreload of matplotlib.dates failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 2\n","]\n","[autoreload of matplotlib.legend failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ImportError: cannot import name 'StepPatch' from 'matplotlib.patches' (/usr/local/lib/python3.7/dist-packages/matplotlib/patches.py)\n","]\n","[autoreload of matplotlib.offsetbox failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: set_figure() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.container failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.legend_handler failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.quiver failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'PolyCollection_kwdoc'\n","]\n","[autoreload of matplotlib.table failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.tri.tricontour failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.tri.trifinder failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.tri.triinterpolate failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.tri.trirefine failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.axes._base failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'Line2D_kwdoc'\n","]\n","[autoreload of matplotlib.axis failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 9\n","]\n","[autoreload of matplotlib.scale failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 1 free vars, not 0\n","]\n","[autoreload of matplotlib.spines failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","KeyError: 'Patch_kwdoc'\n","]\n","[autoreload of matplotlib.axes._secondary_axes failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: set_ticks() requires a code object with 4 free vars, not 0\n","]\n","[autoreload of matplotlib.projections.geo failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: cla() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.projections.polar failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of mpl_toolkits.mplot3d.axes3d failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: _process_unit_info() requires a code object with 1 free vars, not 0\n","]\n","[autoreload of mpl_toolkits.mplot3d.art3d failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of mpl_toolkits.mplot3d.axis3d failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ValueError: __init__() requires a code object with 0 free vars, not 1\n","]\n","[autoreload of matplotlib.backends.backend_agg failed: Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py\", line 247, in check\n","    superreload(m, reload, self.old_objects)\n","ImportError: cannot import name '_check_savefig_extra_args' from 'matplotlib.backend_bases' (/usr/local/lib/python3.7/dist-packages/matplotlib/backend_bases.py)\n","]\n"],"name":"stderr"},{"output_type":"stream","text":["The autoreload extension is already loaded. To reload it, use:\n","  %reload_ext autoreload\n"],"name":"stdout"},{"output_type":"stream","text":["\n","\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","Training and Evaluating Basemodel with: \tLR = 0.0001\tWD = 0\n"],"name":"stdout"},{"output_type":"stream","text":["\n"],"name":"stderr"},{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-30-31f033e19cbb>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mmodel_pipeline\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmain\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexec_model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0mexec_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/content/drive/Shareddrives/EECS 442 - Project/eecs442-proj/model_pipeline.py\u001b[0m in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m     54\u001b[0m         \u001b[0;31m# Setup plots and metrics results storage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     55\u001b[0m         \u001b[0mstats\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 56\u001b[0;31m         \u001b[0mfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmake_training_plot\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'basemodel'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     57\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     58\u001b[0m         \u001b[0;31m# Executee configured number of epochs training + validating\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/content/drive/Shareddrives/EECS 442 - Project/eecs442-proj/utils.py\u001b[0m in \u001b[0;36mmake_training_plot\u001b[0;34m(modType)\u001b[0m\n\u001b[1;32m     34\u001b[0m     \"\"\"\n\u001b[1;32m     35\u001b[0m     \u001b[0;31m# plt.ion()\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 36\u001b[0;31m     \u001b[0mfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msubplots\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfigsize\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     37\u001b[0m     \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msuptitle\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodType\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m' Model Training'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     38\u001b[0m     \u001b[0maxes\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset_xlabel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Epoch'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py\u001b[0m in \u001b[0;36msubplots\u001b[0;34m(nrows, ncols, sharex, sharey, squeeze, subplot_kw, gridspec_kw, **fig_kw)\u001b[0m\n\u001b[1;32m   1175\u001b[0m     \u001b[0;34m.\u001b[0m\u001b[0mFigure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd_subplot\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1176\u001b[0m     \u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msubplots\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1177\u001b[0;31m     \u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0maxes\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1178\u001b[0m     \u001b[0;34m.\u001b[0m\u001b[0mFigure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msubplots\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1179\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py\u001b[0m in \u001b[0;36mfigure\u001b[0;34m(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, clear, **kwargs)\u001b[0m\n\u001b[1;32m    544\u001b[0m \u001b[0;34m@\u001b[0m\u001b[0m_copy_docstring_and_deprecators\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrcdefaults\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    545\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mrcdefaults\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 546\u001b[0;31m     \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrcdefaults\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    547\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_interactive\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    548\u001b[0m         \u001b[0mdraw_all\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/backend_bases.py\u001b[0m in \u001b[0;36mnew_figure_manager\u001b[0;34m(cls, num, *args, **kwargs)\u001b[0m\n\u001b[1;32m   3355\u001b[0m         toolmanager.toolmanager_connect(\n\u001b[1;32m   3356\u001b[0m             \u001b[0;34m'tool_message_event'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3357\u001b[0;31m             lambda event: self.set_message(event.message))\n\u001b[0m\u001b[1;32m   3358\u001b[0m         toolmanager.toolmanager_connect(\n\u001b[1;32m   3359\u001b[0m             \u001b[0;34m'tool_removed_event'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/figure.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, figsize, dpi, facecolor, edgecolor, linewidth, frameon, subplotpars, tight_layout, constrained_layout)\u001b[0m\n\u001b[1;32m    351\u001b[0m         \u001b[0mfontweight\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mweight\u001b[0m \u001b[0;34m:\u001b[0m \u001b[0mdefault\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;34m:\u001b[0m\u001b[0mrc\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0mfigure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtitleweight\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    352\u001b[0m             \u001b[0mThe\u001b[0m \u001b[0mfont\u001b[0m \u001b[0mweight\u001b[0m \u001b[0mof\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mtext\u001b[0m\u001b[0;34m.\u001b[0m \u001b[0mSee\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mText\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset_weight\u001b[0m\u001b[0;31m`\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mpossible\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 353\u001b[0;31m             \u001b[0mvalues\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    354\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    355\u001b[0m         \u001b[0mReturns\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/transforms.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, matrix, **kwargs)\u001b[0m\n\u001b[1;32m   1839\u001b[0m         \u001b[0;32mdef\u001b[0m \u001b[0mtransform_affine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpoints\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1840\u001b[0m             \u001b[0;31m# docstring inherited\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1841\u001b[0;31m             \u001b[0;31m# The major speed trap here is just converting to the\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1842\u001b[0m             \u001b[0;31m# points to an array in the first place.  If we can use\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1843\u001b[0m             \u001b[0;31m# more arrays upstream, that should help here.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/matplotlib/transforms.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m   1749\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1750\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1751\u001b[0;31m         \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1752\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_inverted\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1753\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: super(type, obj): obj must be an instance or subtype of type"]}]}]}